title : Subway Maps

markdown: kramdown

safe: true
lsi: false
pygments: true
auto: true

source: subway-maps
destination: subway-maps

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 10
paginate_path: "/blog/page:num"

production_url : http://subway.map.apievangelist.com/

BASE_PATH : http://subway.map.apievangelist.com/

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
